# Describes the format for available Hubinet-Ops services.

scan_all_packages:

easy_update:
  fields:
    device_id:
      required: true
      selector:
        device:
          filter:
            - integration: hubinet_ops
              model: Container
    autoremove:
      required: false
      default: false
      selector:
        boolean:
    expected_scan_attempt:
      required: false
      selector:
        text:
